version: '3.8'

services:
  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: ethanli-dev123456
      MYSQL_DATABASE: ethanli-dev
      MYSQL_USER: ethanli-dev
      MYSQL_PASSWORD: ethanli-dev123456
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ethanli-dev
      DB_PASSWORD: ethanli-dev123456
      DB_NAME: ethanli-dev
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
